[package]
authors = ["koji88a <koji.hachiya@gmail.com>"]
name = "daemon_sample_rs"
version = "0.1.0"

[dependencies]
chan = "0.1.18"
chan-signal = "0.1.7"
docopt = "0.6.86"
env_logger = "0.3.5"
libc = "0.2.17"
log = "0.3.6"
nix = "0.7.0"
rustc-serialize = "0.3.19"
